create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  external_id varchar(255) not null unique,
  number varchar(255) not null,
  total_sum numeric(10, 2) not null,
  created_at timestamptz not null,
  status varchar(50) not null,
  customer_name varchar(255) not null,
  phone varchar(50),
  email varchar(255),
  city varchar(255),
  delivery_address text,
  items_count integer not null default 0,
  items_summary text
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_city_idx on public.orders (city);
